### ISSUE TITLE
Make ice-pendant take player velocity into account

### ISSUE THREAD

**Issue by Redart15** [bta-team-port/better-with-aether#276]
A player velocity can result and no ice forming. The logic need to adjust to account for velocity up to a max |v| = 10, cause everything afterward might be to much

**Comment by LukeisStuff** [comment]
Fixed with latest push, numbers can be adjusted still

**Comment by Redart15** [comment]
No it is not fixed yet, gona link a recording to it.
https://youtu.be/EEBkZNXMylA

**Comment by Redart15** [comment]
fixed in ad317d573068a55c2ae6ba2f30167056af9cbe7a:
https://youtu.be/VvqRpQAUeec
